Repository UKCloud/AzureStack, pull requests merged in 2019-04, with the labels that each got.

#34 add from other repo
  Operators/PowerShell/modules/MarketplaceManagement/MarketplaceManagement.psm1
  Operators/PowerShell/modules/MarketplaceManagement/README.md
Labels: Language: Documentation, Language: PowerShell, Type: Improvement

#35 Updated invoice estimation module for SQL
  Users/PowerShell/UKCloud for Microsoft Azure Invoice Estimate/AzureStackInvoiceEstimate.psd1
  Users/PowerShell/UKCloud for Microsoft Azure Invoice Estimate/AzureStackInvoiceEstimate.psm1
  Users/PowerShell/UKCloud for Microsoft Azure Invoice Estimate/ExampleSQLFile.csv
  Users/PowerShell/UKCloud for Microsoft Azure Invoice Estimate/README.md
Labels: Language: Documentation, Language: PowerShell, Type: Improvement

#36 Added line about docs.ukcloud.com
  README.md
Labels: Language: Documentation, Type: Improvement

#37 Add Azure Backup Config extension
  Users/Extensions/Windows/ASRCSConfig.ps1
  Users/Extensions/Windows/AzureBackupConfig.ps1
  Users/Extensions/Windows/README.md
Labels: Language: Documentation, Language: PowerShell, Type: Feature

#38 Fix Azure Site Recovery config script - Take 1
  Users/Extensions/Windows/ASRCSConfig.ps1
Labels: Language: PowerShell, Type: Bug

#39 Minor changes to PSexec command
  Users/Extensions/Windows/ASRCSConfig.ps1
Labels: Language: PowerShell, Type: Bug

#40 Fix broken ContainerMapping line
  Users/Extensions/Windows/ASRCSConfig.ps1
Labels: Language: PowerShell, Type: Bug

#41 Minor repo changes
  Operators/PowerShell Modules/InstallModules.ps1
  Operators/PowerShell Modules/IpPools/IpPools.psd1
  Operators/PowerShell Modules/IpPools/IpPools.psm1
  Operators/PowerShell Modules/IpPools/README.md
  Operators/PowerShell Modules/MarketplaceManagement/MarketplaceManagement.psd1
  Operators/PowerShell Modules/MarketplaceManagement/MarketplaceManagement.psm1
  Operators/PowerShell Modules/MarketplaceManagement/README.md
  Operators/PowerShell/InstallModules.ps1
  README.md
  Users/PowerShell Modules/Azure Site Recovery/AzureSiteRecoveryFunctionality.psd1
  Users/PowerShell Modules/Azure Site Recovery/AzureSiteRecoveryFunctionality.psm1
  Users/PowerShell Modules/Azure Site Recovery/README.md
  Users/PowerShell Modules/Azure Stack Kubernetes/AzureStackKubernetes.psd1
  Users/PowerShell Modules/Azure Stack Kubernetes/AzureStackKubernetes.psm1
  Users/PowerShell Modules/Azure Stack Kubernetes/README.md
  Users/PowerShell Modules/InstallModules.ps1
  Users/PowerShell Modules/UKCloud for Microsoft Azure Invoice Estimate/AzureStackInvoiceEstimate.psd1
  Users/PowerShell Modules/UKCloud for Microsoft Azure Invoice Estimate/AzureStackInvoiceEstimate.psm1
  Users/PowerShell Modules/UKCloud for Microsoft Azure Invoice Estimate/ExampleSQLFile.csv
  Users/PowerShell Modules/UKCloud for Microsoft Azure Invoice Estimate/README.md
  Users/PowerShell/InstallModules.ps1
Labels: Language: Documentation, Type: Improvement
